### ISSUE TITLE
createEvent modal duplicates on state change while modal is active

### ISSUE THREAD

**Issue by sarahsvedenborg** [j4hr3n/it2901#120]
Steps to reproduce: 

1. Go to dashboard
2. Click "opprett aktivitet"
3. Lukk modal
4. Klikk "hjem"
5. Klikk "dashboard"
6. Klikk opprett aktivitet 
7. Scroll opp on ned, det er nå to "createEvent" modals.

**Comment by nshung** [comment]
Fixed.
