### ISSUE TITLE
Make a roadmap for app

### ISSUE THREAD

**Issue by sarahsvedenborg** [j4hr3n/it2901#124]
1. What is the current functionality?
2. What is the planned functionality for the next version?

**Comment by j4hr3n** [comment]
Current functionality includes:

- Displaying activities

- Managing profile

To further improve the functionality, we need to find a way to share the database between the app and the webpage. 

The next version of the app will thus include live data, ability to register and log in properly, and a lot of need to have features as that.

**Comment by j4hr3n** [comment]
App and webpage now share a joint database. It is now possible to register and log in properly. Need a discussion on what other features should be implemented in the app.
