### ISSUE TITLE
Make datePicker submit correct date to eventModel

### ISSUE THREAD

**Issue by sarahsvedenborg** [j4hr3n/it2901#163]
The date currently stored in the model is the current date.

**Comment by j4hr3n** [comment]
You probably would benefit from using Moment (http://momentjs.com/). It is already installed in the project if i'm not mistaken. If it hasn't been installed you can find it here: https://atmospherejs.com/momentjs/moment

**Comment by Sibsen1** [comment]
The datepicker is now working (non-reactively) by manually getting it using its built-in getDate method (and likewise setting the date at the start with setDate). 

The input box for the date is no longer needed as a conduit for getting the date and was thus removed.
