### ISSUE TITLE
Reduce amount of info needed during registration to the bare necessity

### ISSUE THREAD

**Issue by BabakFarshchian** [j4hr3n/it2901#171]
E.g. the user does not need to upload a photo. Use default.

**Comment by nshung** [comment]
Reduce to just username, email and password.. may be? @Sibsen1

**Comment by BabakFarshchian** [comment]
Most services now use email address as user name. So I suggest you keep email address and password as minimum registration data.

**Comment by nshung** [comment]
Done!
