### ISSUE TITLE
Vise fram treningsdata, visualisering av acitivty index, grafer

### ISSUE THREAD

**Issue by emilsa** [j4hr3n/it2901#98]

**Comment by BabakFarshchian** [comment]
The data that is stored about a user includes the following list. I am working on translating this to something that users can understand. Not all this data needs to be visualized.

• Total, maximum and median duration of locomotion bouts
• Number of strides
• Stride time and length
• Mean walking speed
• Distance walked per bout
• Stride time, length and speed variability
• SD of acceleration
• Stride regularity
• Index harmonicity (spectral measure)
• Frequency variability (spectral measure)
• Harmonic ratio (spectral measure)
• Dominant frequency, amplitude and width (spectral measure)
• Sample and permutation entropy (non-linear measure)
• Local dynamic stability (non-linear measure)

**Comment by sarahsvedenborg** [comment]
The fields intended for the user to see are entered into the system in Norwegian, while the fields which only make sense to physicians are left in English.
